# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('slug', models.CharField(max_length=200, verbose_name='\u7f51\u5740')),
                ('body', models.TextField(verbose_name='\u5185\u5bb9')),
                ('pub_dat', models.DateField(verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('pub_time', models.TimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
            ],
        ),
    ]
