# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20180824_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='tags',
            field=models.CharField(choices=[('linux', 'ubuntu linux'), ('ucos', 'rtos rutine'), ('mpu', '\u5904\u7406\u5668'), ('mcu', '\u5355\u7247\u673a'), ('qt', 'qt \u76f8\u5173\u7684\u4e1c\u897f')], default='linux', max_length=20, verbose_name='\u6807\u7b7e'),
        ),
    ]
